<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <PackageId>GovUK.Dfe.SchoolsDigitalApp</PackageId>
    <Title>DfE Schools Digital app</Title>
    <Description>Schools Digital repository template for an ASP.NET Core application.</Description>
    <Authors>DfE Schools Digital</Authors>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageProjectUrl>https://github.com/DFE-Digital/CSharp-.NET-Template</PackageProjectUrl>
    <RepositoryUrl>https://github.com/DFE-Digital/CSharp-.NET-Template</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <MinVerTagPrefix>v</MinVerTagPrefix>
    
    <PackageType>Template</PackageType>
    <TargetFramework>net10.0</TargetFramework>
    <IncludeContentInPack>true</IncludeContentInPack>
    <IncludeBuildOutput>false</IncludeBuildOutput>
    <ContentTargetFolders>content</ContentTargetFolders>
    <NoWarn>$(NoWarn);NU5128</NoWarn>
    <NoDefaultExcludes>true</NoDefaultExcludes>
    
  </PropertyGroup>

  <PropertyGroup>
    <LocalizeTemplates>false</LocalizeTemplates>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.TemplateEngine.Tasks" Version="*" PrivateAssets="all" IsImplicitlyDefined="true"/>
    <PackageReference Include="MinVer" Version="7.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <Content Include="content\**\*" Exclude="content\**\bin\**;content\**\obj\**;content\src\SDApp.Web\wwwroot\**\*;content\src\SDApp.Web\lib\**\*" />
    <Compile Remove="**\*" />
  </ItemGroup>

  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="" />
  </ItemGroup>

</Project>
